version: '2'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4040:4040
    environment:
      PORT: 4040
      MONGO_HOST: mongodb://localhost/node-docker-seed
  mongo:
    image: "mongo:3.6.0"
    ports:
      - "27017:27017"